# https://mvnrepository.com/artifact/com.github.spotbugs/spotbugs-annotations
spotBugsVersion=4.10.4
# https://mvnrepository.com/artifact/io.github.classgraph/classgraph
classGraphVersion=4.8.194
# https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core
log4jVersion=2.26.1
# https://mvnrepository.com/artifact/com.google.guava/guava
guavaVersion=33.7.1-jre
# https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
junitVersion=6.1.3
# https://mvnrepository.com/artifact/org.junit-pioneer/junit-pioneer
junitPioneerVersion=2.3.0
# https://mvnrepository.com/artifact/org.mockito/mockito-junit-jupiter
mockitoVersion=5.23.0
# https://mvnrepository.com/artifact/org.hamcrest/hamcrest-core
hamcrestVersion=3.0
